version: '3.8'

services:
  api:
    build:
      context: ./mnist-backend
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    restart: unless-stopped

  streamlit:
    build:
      context: ./mnist-frontend
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped 